// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import { PGlite } from '@electric-sql/pglite';
import { PrismaPGlite } from 'pglite-prisma-adapter';

export default defineConfig({
  schema: 'prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
  ...(process.env.NODE_ENV === 'test'
    ? {
        migrate: {
          adapter(env) {
            const client = new PGlite({ dataDir: env.DATABASE_DIR });
            return new PrismaPGlite(client);
          },
        },
        studio: {
          adapter(env) {
            const client = new PGlite({ dataDir: env.DATABASE_DIR });
            return new PrismaPGlite(client);
          },
        },
      }
    : {}),
});
